// 02_Learn_VueJs/08_learn_pinia/src/views/Home.vue
<template>
  <h2>Home组件</h2>
  <button @click="addCount">count+1</button>
  <h3>当前计数:{{counterStore.count}}</h3>
  <h3>当前计数:{{count}}</h3>
</template>

<script setup>
import { storeToRefs } from 'pinia'
import { useCounter } from '@/stores/counter'
import { toRefs } from 'vue';

const counterStore = useCounter()

// const { count } = toRefs(counterStore)
const { count } = storeToRefs(counterStore)

const addCount = () => {
  counterStore.count++
}
</script>

<style scoped lang="scss">
</style>

// 03_Learn_React18/02_learn_react_scaffold/src/views/Home.jsx
import React, { Component } from 'react'

export default class Home extends Component {
  constructor(){
    super()
    this.state = {
      counter:0
    }
  }
  changeCount(count){
    this.setState({
      counter:this.state.counter + count
    })
  }
  render() {
    return (
      <div>
        <h3>Home组件,当前计数{this.state.counter}</h3>
        <button onClick={() => this.changeCount(1)}>+1</button>
        <button onClick={() => this.changeCount(-1)}>-1</button>
      </div>
    )
  }
}
