// 03_Learn_React18/03_learn_component/src/05_组件通信-子传父/App.jsx
import React, { Component } from 'react'
import AddCounter from './AddCounter'
import SubCounter from './SubCounter'

export default class App extends Component {
  constructor(){
    super()
    this.state = {
      counter:0
    }
  }
  changeCounter(count){
    this.setState({
      counter:this.state.counter + count
    })
  }
  render() {
    return (
      <div>
        <h2>当前计数:{this.state.counter}</h2>
        <AddCounter add={(count) => this.changeCounter(count)} />
        <SubCounter sub={(count) => this.changeCounter(count)} />
      </div>
    )
  }
}

// 02_Learn_VueJs/03_learn_vue_components/src/03_组件通信_子传父/App.vue
<template>
  <h2>当前计数:{{counter}}</h2>
  <add-count @add="add" />
  <sub-count @sub="sub" />
</template>

<script>
import AddCount from './AddCount.vue'
import SubCount from './SubCount.vue'
export default {
  components:{
    AddCount,
    SubCount
  },
  data(){
    return {
      counter:0
    }
  },
  methods:{
    add(num){
      this.counter += num
    },
    sub(num){
      this.counter -= num
    }
  }
}
</script>

<style>

</style>
